### ISSUE TITLE
branch fix/vectorised

### ISSUE THREAD

**Issue by basegpu** [OP-DSL/OP2-Common#124]
The branch `fix/vectorised` is quite a bit ahead of the master and resolves a bug in passing arguments in vectorised form.

Since October 2017 this branch is not active and I was wondering whether this branch could be merged into master?

**Comment by basegpu** [comment]
I don't understand, there was a merge request for this branch, but then it got merged into `fix/vecorised2` and later this merged into `master`.

The branch overview tells me:
* `fix/vectorised2` is 50 commits behind `master`, and 0 ahead -> ok
* `fix/vectorised` is 52 commits behind, but 68 ahead of the `master`.

`fix/vectorised` shouldn't be ahead of the master, right?

I got aware of this, by getting wrong values in the passed arguments in vectorised form when using the `master`. switching back to `fix/vectorised` it works, but other features are missing then from `master` of course.

**Comment by reguly** [comment]
Hmm, there was a problem when we tried to rebase the branch on master, because a lot of commits suddenly appeared twice. So we rolled back locally and pushed the commits to a different branch, but apparently missed some.

**Comment by reguly** [comment]
Any idea about the difference between the two? Something in generated code?

**Comment by basegpu** [comment]
generated code is identical

**Comment by basegpu** [comment]
I ran again some tests...and I found the error.
The error was from my side, there was a problem the way the mapping `*int` was allocated.
Everything ok, the functionalities of `fix/vectorised` are all in master, I apologise for any inconveniences.
cheers

**Comment by reguly** [comment]
No worries, thanks for investigating this!
