### ISSUE TITLE
[Feature request] type declaration in dat declaration from h5

### ISSUE THREAD

**Issue by basegpu** [OP-DSL/OP2-Common#132]
When calling
~~~c
op_decl_dat_hdf5(op_set set, int dim, char const *type, char const *file, char const *name);
~~~
the passed argument *type* must match the datatype of the according dataset defined in the h5 container (see `op2/c/src/externlib/op_hdf5.c`, line 274 ff)
~~~c
const char *typ = dset_props.type_str;
if (!op_type_equivalence(typ, type)) {
  op_printf("dat.type %s in file %s and type %s do not match\n", typ, file, type);
  exit(2);
}
~~~
Therefore the declaration call fails in case that the two types do not match.

The situation that I face is:
Given a fully defined model in a h5 container, I'd like to run the simulation with single or double precision (the according simulation binaries were successfully compiled). Calling the double precision binary works perfectly since the datasets in the h5 container are stored as doubles. Calling the single precision binary fails, of course, because of the above mentioned restriction of type equivalence.

Is there a possibility to relax this restriction (only between single and double) and provide some automatic type conversion in the `op_decl_dat_hdf5` call?

**Comment by reguly** [comment]
Turns out HDF5 supports automatic type conversion! I have added support for this for the MPI and non-MPI backends - please test the feature/hdf5_conversion branch and let me know if it works okay for you. If so, we'll pull it into master

**Comment by basegpu** [comment]
thx for taking care of the conversion issue!

Where is the *feature/hdf5_conversion* branch? I cannot see it...

**Comment by basegpu** [comment]
ok 😄

**Comment by reguly** [comment]
Please check now :)

**Comment by basegpu** [comment]
tested the branch `feature/hdf5_conversion`.

the conversion works as expected, thx!

**Comment by basegpu** [comment]
We are still missing *actual single precision operations* in our compiled simulation binaries. Is there anything else needed besides declaring all `op_dat` as floats?

**Comment by reguly** [comment]
In part yes, also in the parallel loops, for the ops_arg_dat, you need to put float. Of course the user kernels should accept floats as arguments instead of double.

**Comment by basegpu** [comment]
We have replaced all `double` and `"double"` by `float` and `"float"`, respectively, in all `op_decl_dat` calls, `op_arg_dat` definitions inside the `op_par_loop` calls, and inside the kernels as well. But without success so far (no change in calculation time, neither cpu not gpu).

**Comment by reguly** [comment]
I am not sure what could be going on without seeing the code - if the generated code indeed says float everywhere and you are getting the right results, then it should be running in single precision. We do have applicaitons in float, and they work fine… For some parts of the code, particularly where you have indirect increments, going from double to float may not really improve performance much.

**Comment by basegpu** [comment]
single precision code is running and the performance gain is as expected.
