### ISSUE TITLE
removing #includes in cuda files

### ISSUE THREAD

**Issue by basegpu** [OP-DSL/OP2-Common#133]
after having removed the includes of the kernel header files `*.h` from the generated cuda code (which actually works perfectly), why are the includes added again in case of having more than ONE include?

line 321 ff, op_gen_cuda_simple.py
~~~python
if CPP:
  includes = op2_gen_common.extract_includes(kernel_text)
  if len(includes) > 1:
    for include in includes:
      code(include)
    code("")
~~~

This leads to compile errors of the cuda kernels in case you have more than one includes...?!

**Comment by aowenson** [comment]
That is a mistake, includes should be added if length is greater than zero. I will submit a patch.

The reason this is done at all is to carry over any dependencies of the kernel, such as macro definitions or inlined functions. What is the compilation error that you experience?

**Comment by basegpu** [comment]
but why should the includes be removed at all if you want to carry them over?

**Comment by aowenson** [comment]
The includes are "extracted" (copied really) from the source kernel, and inserted into head of the constructed .cu file. There is no removal.

**Comment by basegpu** [comment]
ok, this makes sense.

We have header files with utility functions. In case of compiling for cuda devices, we run our own translation step, after op2 translation and before invoking the compiling. What we do:
- copy the utility function headers to `utilityFunctions.cu` and convert the function declarations to something like `__device__ void utility1()`
- we add these new cuda files to the source list
- we add global includes of these new cuda files in the `_kernels.cu`
- we then extract all local includes of the old header files 'utilityFunctions.h` in the actual `_kernel.cu` files

this worked only because of the *erroneous* removal of the includes in the op2 translator... ;) we will add the removal to our own translation step. or do you see another (simpler) solution?

**Comment by aowenson** [comment]
That is a process that OP2 should be able to perform (eventually). Can you clarify what you mean by utility function, and whether they are invoked from within loops? Maybe provide an example?

**Comment by basegpu** [comment]
Given the source file `kernel_doStuff.h` with the kernel implementation
~~~C
#include "utilities.h"

inline void kernel_doStuff (...) {
    dummyFunction();
}
~~~

wherein we call an inline function defined in another source file `utilities.h`

~~~C
#ifndef UTILITIES_H_
#define UTILITIES_H_

inline void dummyFunction() {
    ...
}

#endif
~~~

Running the *OP2* generator, the translated cpu code works out of the box, i.e. no changes regarding the includes. But the translated cuda code needs some adaptions (see above).

**Comment by reguly** [comment]
There is now a supported way of calling functions from within user kernels - please see the code in https://github.com/OP-DSL/OP2-Common/tree/master/apps/c/jac1/dp you basically have to put all the functions in user_types.h (or at least include them) and add the OP_FUN_PREFIX macro, which gets #defined to __device__ when targeting GPUs. You may need "static" too, otherwise you'll end up with multiple definition errors at linking time. Would that address your need?

**Comment by basegpu** [comment]
it worked! thx
