### ISSUE TITLE
OP_MAX in C

### ISSUE THREAD

**Issue by vlukas23** [OP-DSL/OP2-Common#140]
Dear OP2 developers,
I am testing the option of OP_MAX in a op_par_loop (C framework), e.g.
op_arg_gbl(&dzMax, 1, double, OP_MAX )

the python translator seems to have a typo (op2_gen_openmp_simple.py on line 483)
elif  accs(m)==OP_MAX:
instead of
elif  accs[m]==OP_MAX:

with this change translation and compilation works, but the data array dzMax is not affected by OP_MAX. What is the status of the OP_MAX feature?

**Comment by reguly** [comment]
Thank you for catching this - I created a pull request to fix this.

**Comment by vlukas23** [comment]
Thank you for fixing this. However, I didn't get OP_MAX to work yet.
Is this following general usage of OP_MAX possible within a while loop:

double dzMax = 99.9;
double dzEpsilon = 0.1;
while (dzMax > dzEpsilon){
      op_par_loop( kernelFunction, name,
      op_sets[set_A],
      ...
      op_arg_gbl(&dzMax, 1, double, OP_MAX  ));
}

dzMax is then calculated in the loop, but was globally unchanged (remaining 99.9).

**Comment by reguly** [comment]
the way the maximum is calculated  is the maximum of the input value (99.9 for you) and the values calculated at each set element. If the values calculated at the elements are less than 99.9, then yes it should go unchanged. Try setting dzMax to something small just before calling the op_par_loop.

**Comment by vlukas23** [comment]
Thank you a lot, got it to work now!

**Comment by vlukas23** [comment]
the global reduction of OP_MAX works well for Sequential and OpenMP backends. In the case of CUDA, however, debugging a kernel (similar to the example above) I didn't find the correct global maximum values. I had a look at the c/python translator but couldn't find anything.

**Comment by reguly** [comment]
Our internal tests pass with the current version. Could you share the op_par_loop in question?

**Comment by vlukas23** [comment]
Thanks for this feedback, so there must be an implementation error on my side.

**Comment by reguly** [comment]
Not necessarily... If you can share the loop in question, I can check the
code generated

**Comment by vlukas23** [comment]
Indeed, conceptual error in implementation. The problem was that I had another variable with RW access, which is used to calculate dzMax (global reduction), on the cuda backend this gave different results. Splitting this into two op_par_loops works now!
