### ISSUE TITLE
cuda function attributes

### ISSUE THREAD

**Issue by basegpu** [OP-DSL/OP2-Common#149]
why is the `__host__` attribute put to the user defined functions? isn't it assumed that they all run on the device?

~~~C
#define OP_FUN_PREFIX __host__ __device__
#include "../user_types.h"
~~~

we have problems with cuda specific math functions that are not available on the host...

**Comment by reguly** [comment]
Please see #150 - this will let you define OP_FUN_PREFIX to just __device__ during your make process

**Comment by basegpu** [comment]
sounds reasonable to me, many thx!

**Comment by basegpu** [comment]
setting `OP_FUN_PREFIX` in cmake was not straight forward. After some struggles I finally found this: https://stackoverflow.com/questions/2843075/cmake-target-specific-preprocessor-definitions-for-cuda-targets-seems-not-to-wo

short summary what did work: before defining the OP target by `op2_application`, adding the definition directly to the nvcc flags by

`set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS} "-DOP_FUN_PREFIX=__device__")`
