### ISSUE TITLE
Issue in compiling OP2 fortran OpenMP

### ISSUE THREAD

**Issue by chintagunta** [OP-DSL/OP2-Common#169]
**Dear OP2 team, 

I am unable to get the OP2 Fortran library version to compile. This is the output.
Thank you for your help. Tried uncommenting the commented lines in 1312 & 1368.
Kind regards,
Dr Abhishek C
**

/home/abhi/OP2/op2/fortran/src/op2_for_declarations.F90:1367:54:

     op_arg_gbl_python_i4_2dim = op_arg_gbl_c ( c_loc (int_ptr(dat)), dim, C_CHAR_'int'//C_NULL_CHAR, 4, access-1 )
                                                      1
Error: Argument X at (1) to C_LOC shall have either the POINTER or the TARGET attribute
/home/abhi/OP2/op2/fortran/src/op2_for_declarations.F90:1311:54:

     op_arg_gbl_python_r8_2dim = op_arg_gbl_c ( c_loc (real_ptr(dat)), dim, C_CHAR_'double'//C_NULL_CHAR, 8, access-1 )
                                                      1
Error: Argument X at (1) to C_LOC shall have either the POINTER or the TARGET attribute
Makefile:321: recipe for target 'f_openmp' failed
make: *** [f_openmp] Error 1

**Comment by reguly** [comment]
Dear Dr. Abhishek,

I assume you are using GCC/GFortran to compile - what version? It seems different versions of GFortran have different requirements to handle this issue. There are 3 occurrences of `#ifdef __GFORTRAN__` in `op2/src/op2_for_declarations.F90` which cause this trouble. Please try changing them to something like `#ifdef XX__GFORTRAN__` and see if the compilation goes through. We will try and see which version of GFortran require this workaround and which do not.

**Comment by chintagunta** [comment]
Dear Dr Reguly,

The fix helped with the compilation (I am using GCC 7.5.0). Thank you for your prompt and appropriate response. The change in op2_for_decalrations.F90 from __GFORTRAN__ to XX__GFORTRAN__ has resolved the issue.

Kind Regards,
Dr Abhishek

**Comment by gihanmudalige** [comment]
Closing, issue fixed.
