### ISSUE TITLE
Missing kernel invocations in MPI setting

### ISSUE THREAD

**Issue by m-8k** [OP-DSL/OP2-Common#170]
Currently, the code that the Python translator produces only calls the kernel if the MPI-local size of the set is greater than zero:

https://github.com/OP-DSL/OP2-Common/blob/fe969e0d7be7818791f79c0038714641e5c78e3c/translator/c/python/op2_gen_seq.py#L235

However, in the MPI setting, the kernel needs to be called even if only the import execute halo is nonempty.

As far as I can see the if statement should therefore actually check whether `set_size > 0`. If this is correct then it might be possible to drop the if statement entirely.

**Comment by reguly** [comment]
@m-8k #172 (merged into master now) should address this for all parallelisations. Marking as completed

**Comment by m-8k** [comment]
@reguly Thanks for fixing the issue so quickly!
