### ISSUE TITLE
QuickSort for arrays of length zero

### ISSUE THREAD

**Issue by m-8k** [OP-DSL/OP2-Common#173]
The `quickSort` implementation currently assumes that the array to sort has nonzero length because it accesses an element in any case:

https://github.com/OP-DSL/OP2-Common/blob/d03e58fd759143258e3b9d697955b6ab1c2fe339/op2/c/src/externlib/op_util.c#L177

This function is used in `is_onto_map`:

https://github.com/OP-DSL/OP2-Common/blob/17eb01ce6160115bd0bfc4cf8a37fec5d7165697/op2/c/src/mpi/op_mpi_core.c#L363

In case `map->from->size == 0` this function call does not satisfy `quickSort`'s precondition.

I would suggest to avoid the unconditional access in `quickSort` to support this special case. Let me know if you would like me to submit a PR.

**Comment by gihanmudalige** [comment]
Fixed, closing.
