### ISSUE TITLE
"op_decl_dat_char" reports error for sets of MPI-local size zero

### ISSUE THREAD

**Issue by m-8k** [OP-DSL/OP2-Common#174]
The function `xmalloc` currently returns a `NULL` pointer if zero bytes are requested. Therefore, `op_decl_dat_char` reports an error in the special case where the MPI-local size of a set is zero:

https://github.com/OP-DSL/OP2-Common/blob/d03e58fd759143258e3b9d697955b6ab1c2fe339/op2/c/src/mpi/op_mpi_cuda_decl.c#L150

As far as I can see this error message is only desirable if `xmalloc` returned `NULL` because it failed to allocate memory of nonzero size. Let me know if you would like me to submit a pull request.

**Comment by gihanmudalige** [comment]
Closing, as this is fixed now.
