### ISSUE TITLE
HDF5 error handler not reset correctly

### ISSUE THREAD

**Issue by m-8k** [OP-DSL/OP2-Common#187]
If I understand correctly, the following code snippet intends to store the "automatic error stack traversal function" ([hdf5 documentation](https://portal.hdfgroup.org/display/HDF5/H5E_GET_AUTO)) and return it to the caller.

https://github.com/OP-DSL/OP2-Common/blob/88bb46ef545df852da3861e8264bbc1d5bcffa97/op2/c/src/externlib/op_hdf5_common.c#L59-L61

However, I think it actually stores the function to the local copy `old_func` of the parameter, so it's not passed to the caller of `H5error_off`. This means that the function will not be reset correctly later. The same applies to the second parameter.

I would suggest to fix this by changing the function signature to:
```c
void H5error_off(H5E_auto_t* old_func, void **old_client_data)
```
 Of course, I am happy to submit a pull request.

**Comment by reguly** [comment]
Yes, that looks like it’s going to be lost. Please do submit the pull request! Thanks!
