### ISSUE TITLE
Translator requires Python 2

### ISSUE THREAD

**Issue by m-8k** [OP-DSL/OP2-Common#191]
Currently, the Python translator requires Python 2 to run (for instance, the `print` statement is used). 

Since Python 2 [is no longer supported](https://www.python.org/doc/sunset-python-2/), it would be great if the translator scripts were compatible with Python 3.

**Comment by reguly** [comment]
Indeed, this is long overdue... please see #192

**Comment by reguly** [comment]
This is now merged it.
