### ISSUE TITLE
Invalid code generated if both optional arguments and vector maps are used

### ISSUE THREAD

**Issue by m-8k** [OP-DSL/OP2-Common#193]
The Python generators `op2_gen_seq` and  `op2_gen_openmp_simple` produce invalid code if both optional arguments and vector maps are used.

More precisely, the following code snippets use the parameter `arg` with ID `g_m` in the generated `if` condition.

https://github.com/OP-DSL/OP2-Common/blob/5aa899af6690ef7630945eaa674e271f23c92115/translator/c/python/op2_gen_seq.py#L261-L264

https://github.com/OP-DSL/OP2-Common/blob/5aa899af6690ef7630945eaa674e271f23c92115/translator/c/python/op2_gen_openmp_simple.py#L352-L355

If I am not missing something then this is problematic for vector maps, since some of the IDs `g_m` need to reference the same array parameter.

Most likely, the problem can be fixed by retrieving the ID of the parameter using `invmapinds` instead of using `g_m` directly. Of course, I am happy to submit a pull request.

**Comment by reguly** [comment]
Thanks - looking into this.

Just a word of caution - vector maps do work, but they are not very good for performance. So if it's not much trouble listing the args, it will perform better.

**Comment by reguly** [comment]
@m-8k  I am struggling to reproduce the issue. When vector maps are used, nargs, and all the arrays are inflated to have elements accounting for each element in the vector.
Can you post an op_par_loop call where this produces issues?

**Comment by m-8k** [comment]
@reguly Thanks for looking into the issue. When I run the code generator for the following example, it generates `if (arg1.opt)`, but `arg1` is not a parameter of the generated function.

```c
op_par_loop(
    abc,
    "abc",
    set,
    op_opt_arg_dat(true, dat, -2, map, 1, double, OP_READ)
);
```

**Comment by reguly** [comment]
Thanks - please see #195
