### ISSUE TITLE
support of mixed executables

### ISSUE THREAD

**Issue by mbuergle** [OP-DSL/OP2-Common#216]
Dear OP2 team, we were wondering if you intend to support mixed executables by combining  CUDA and non-CUDA backends, i.e. that certain kernels could run on the CPU and others on GPU?

**Comment by reguly** [comment]
You can mix and match certain generated kernels, while using the GPU backend, it should work (we often debug things this way). So if you generated sequential and CUDA kernels, you can compile and use them together. You can't mix OpenMP and CUDA though, due to op_plan creation.

**Comment by mbuergle** [comment]
Unfortunately, we encounter duplicate symbols when combining CUDA and sequential kernels, since OP2-CUDA requires the file op_cuda_rt_support.c and OP2-SEQ requires op_dummy_singlenode.c. Both of these file define ` int op_mpi_halo_exchanges(op_set set, int nargs, op_arg *args)`. Is this avoidable?

**Comment by reguly** [comment]
OP2-SEQ should not require op_dummy_singlenode.c when op_cuda_rt_support.c is present - all the necessary functions should be there in op_cuda_rt_support.c.

**Comment by reguly** [comment]
Sorry about that, this is a newly introduced bug - op_cuda_rt_support.c should have included this method. I just pushed a fix to the master branch.

**Comment by m-8k** [comment]
Thank you @reguly ! - Your fix solved the issue with the "sequential" kernels.

**Comment by reguly** [comment]
Does this resolve the overall issue as well?

**Comment by m-8k** [comment]
Of course it would be great if it were possible to combine OpenMP and CUDA kernels, too, but I understand from your reply above that this is not supported at the moment.

Could this use case be supported in the future or is it out of scope for now?

**Comment by reguly** [comment]
For lack of a relevant use case, it has not been on the TODO list before, since we only used this “mixing” of kernels for debugging purposes. What would be your use case for this?

**Comment by m-8k** [comment]
The idea was to improve performance by scheduling some multi-threaded kernels on the CPU, but we'll benchmark first to determine whether this indeed looks promising in our use case.

Thank you very much for the support, I think you can close this issue.
