### ISSUE TITLE
what's the used version of HDF5 in OP2?

### ISSUE THREAD

**Issue by lj-cug** [OP-DSL/OP2-Common#224]
Dear Sir:
     I cannot find the information about the used version of HDF5 in OP2? The development of HDF5 is advanced in recent years with some new API. The compatibility should be considered.
Best Regards
Li Jian

**Comment by reguly** [comment]
Are you having issues? If so, what are they? I just tried the latest hdf5 release 1.12.1, and it seems to work fine. If you are using OpenMPI, in some systems it might have problems with MPI-IO and HDF5, and get stuck, then try adding the `-mca io ^ompio` parameter to mpirun.

**Comment by lj-cug** [comment]
No compling problem happened when using HDF5 1.12, and I notice some new features including GDS and Async-IO in HDF5 1.13.  The extension will be feasible. Thank you!
