### ISSUE TITLE
fatal error: 'path/OP2-Common/op2/c/include/op_cuda_reduction_supp.h' file not found

### ISSUE THREAD

**Issue by zongjing1998** [OP-DSL/OP2-Common#230]
Dear Sir:
When I use op2-clang to generate CUDA code, there is a problem：
**fatal error: 'path/OP2-Common/op2/c/include/op_cuda_reduction_supp.h' file not found**
I search for the file in OP2-Common, but I can't find it.
Could you give me the file 'op_cuda_reduction_supp.h', please?

skeleton_kernels.cu:
//
// auto-generated by op2-clang
//
// header
#include "op_lib_cpp.h"
#include "op_cuda_rt_support.h"
#include "op_cuda_reduction.h"
**#include "op_cuda_reduction_supp.h"**

**Comment by reguly** [comment]
Hello,

OP2-Clang is no longer maintained, please use the python-based translator in this repository. For trying to reproduce the old results, @bgd54 may know where to find this file - probably a separate branch.

**Comment by gihanmudalige** [comment]
Just to add to this, the python based code generator is getting a redevelopment on a different branch. We plan to have it merged in soon .So do watch this space ! But hopefully the translator in the master branch will support the work you are doing. Do let us know of any further issues.

**Comment by bgd54** [comment]
Hello,
It seems that I've lost that file somewhere along the way. That header reduced the amount of code we needed to generate. 
I've tried to recreate the file in
https://github.com/OP-DSL/clang-op-translator/blob/temp/op_cuda_reduction_supp/op2_ext/op_cuda_reduction_supp.h
