### ISSUE TITLE
Different behaviour between single node vs MPI when declaring dats with a null data pointer

### ISSUE THREAD

**Issue by TobyFlynn** [OP-DSL/OP2-Common#242]
Currently when you declare a dat with a null data pointer for non-MPI backends this returns a valid dat that OP2 has allocated memory for itself. However, for MPI backends a null op_dat is returned instead. This [commit](https://github.com/TobyFlynn/OP2-Common/commit/d5cfc075b71a63b8405197fa9b3452efe915d120) changes things so that all backends return a valid dat when a null dat pointer is passed to op_decl_dat but before I open a pull request I wanted to check if we want the same behaviour for non-MPI and MPI backends in this case? I don't know if some applications rely on this behaviour for MPI apps

**Comment by reguly** [comment]
Good question @bozbez is this something we rely on under the hood anywhere in Hydra?

**Comment by bozbez** [comment]
No shouldn't be, our dat declaration is based on hyd_all calls.

**Comment by reguly** [comment]
Then I think @TobyFlynn you should go ahead with the proposed change!
