### ISSUE TITLE
op_opt_arg_dats only supported with the Fortran API

### ISSUE THREAD

**Issue by gihanmudalige** [OP-DSL/OP2-Common#88]
The actual need for having op_opt_arg_dats was Rolls Royce Hydra. We have not had any C/C++ API based application using op_opt_arg_dats yet. As such they are yet to be implemented on the C side code generators and back-end libs.

**Comment by basegpu** [comment]
How is the status concerning the `op_opt_arg_dats` on the C side (generator and back-end libs)? This feature would simplify things enormously for our application...

**Comment by basegpu** [comment]
It seems to me, that `op_opt_arg_dats` functions are implemented in the back-end libs, but the python translator cannot handle the optional arguments appropriately?

**Comment by basegpu** [comment]
If it were part of the C translator as well, that would be fantastic! Please let me know if I can help/contribute in some way...

**Comment by reguly** [comment]
I have pushed an initial version - please see the feature/c_arg_opt branch. It currently does not yet support vectorized arguments (negative dim), but perhaps you can start experimenting. Please give it a try, and let me know. It’s entirely possible it will break, I have only tested this on two simple kernels.

**Comment by basegpu** [comment]
thx, we will test it.

just to make sure: if the flag is true, the data is passed to the kernel we have access to it inside the kernel. If the flag is false, the data is NOT passed to the kernel and therefore no chance to access it inside the kernel?

**Comment by reguly** [comment]
The only restriction is that if the flag is false, you may not dereference the pointer that is passed to the user kernel, otherwise you will get a segfault.

**Comment by basegpu** [comment]
i.e. the performance of executing the two kernels are almost the same?

1. kernel with 3 regular op_arg_dat
2. same kernel, but in addition to the 3 regular op_arg_dat, another 10 op_opt_arg_dat are passed, all flags are false though.

**Comment by reguly** [comment]
The performance should be better, because you are not moving all that extra data.

**Comment by basegpu** [comment]
perfect!
we will give a feedback to the version implemented on the branch.

**Comment by basegpu** [comment]
first tests succeeded! the behaviour is as expected. I tested arguments with direct access and indirect access, but no vectorization of arguments.

The vectorization of arguments is not of great importance for us right now, but might be in future. What are the plans concerning this?

Another question: what is the preferred way to check if an argument is passed inside the kernel? by checking for `NULL` pointer or via a global constants?

**Comment by reguly** [comment]
The vectorization support needs some further work, but probably not too much. Just haven’t gotten around to doing it yet.

Checking for optionals: checking for NULL is not going to be reliable (particularly on the GPU) - I suggest passing the logical as an ops_arg_gbl, or perhaps making it a global constant.

**Comment by vlukas23** [comment]
positive feedback from our side: the version without vectorized arguments (negative dim) works perfectly passing the logical by ops_arg_gbl of type int.

**Comment by reguly** [comment]
Good to hear! I will work on getting the vectorized arguments supported too.

**Comment by reguly** [comment]
I have pushed in some support for this - please fetch the latest version of this branch and see if it works. I don't yet have a test where the opt flag is actually false, so if there are any segmentation faults that's probably to blame.

**Comment by basegpu** [comment]
first tests for the vectorised AND optional arguments succeeded. THX!

**Comment by basegpu** [comment]
further tests all passed:
*  tested backends: sequential, openmp_simple, cuda_simple, mixed cuda-seq and cuda-openmp.
*  no seg fault in case of opt flag set to false.

Is there any functionality concerning the optional argument that is yet missing?

**Comment by reguly** [comment]
I think I have covered all the cases (I did a minor update yesterday for kernels that use OP_RW and OP_INC indirectly, this was missing). I asked Gihan to run the tests, and we’ll be merging this into master soon.

**Comment by gihanmudalige** [comment]
Closing. I assume this has been fixed for a long time now.
